### ISSUE TITLE
页面细节

### ISSUE THREAD

**Issue by elrrrrrrr** [SegmentFault/report#130]
* 个人页加入时间样式不统一，没有对齐，建议加上
```css
.text-muted {
    margin-left: 20px;
}
```
* 静态资源没有添加map
```sh
GET http://static.segmentfault.com/build/user/js/jquery.min.map; 404 (Not Found) 
```
* 注册流程提示**非常不明显**
无法直接用第三方账号评论，注册邮件提示(页面最上方没有出现)，导致我注册了4次 

页面问题都是细节，希望对网站提升有所帮助 :smile:
