### ISSUE TITLE
建议 -- 字体

### ISSUE THREAD

**Issue by shrekuu** [SegmentFault/report#227]
### 建议

弄弄字体吧, 推荐这样写:
```css
body {
    font-family: "Helvetica neue",Helvetica,Tahoma,"Pingfang SC","Hiragino Sans GB","Lantinghei SC","WenQuanYi Micro Hei","Microsoft Yahei",sans-serif;
}
```

> "Pingfang SC"  -> Mac OSX El Capitan, 中文名 "苹方"
> "Hiragino Sans GB"   -> Mac OSX Yosemite 及以下 
> "Lantinghei SC" -> Mac OSX 若没以上两个就试这个(这项可略去) 
> "WenQuanYi Micro Hei" -> Ubuntu 
> "Microsoft Yahei" -> windows vista 以上

也可再加上字体优化的一个, 在 webkit 内核浏览器里笔划会平滑些:
```css
body {
    -webkit-font-smoothing: antialiased;
}
```
